name: biolo_app
description: "Projeto dos intermediarios."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
 
  google_nav_bar: ^5.0.7
  sqflite: ^2.4.1
  line_icons: ^2.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  cupertino_icons: ^1.0.8
  get_it: 
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true

  assets:
  - assets/splah_json/splasr.json
  - assets/img/
  - assets/img/casa05.jpeg
  - assets/img/fundo01.jpeg
  - assets/img/homepage/House.png
  - assets/img/icon/
 
  


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
